### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by GreihMurray**

### CODE REVIEW

**Comment by abeiler7** [comment]
Few questions. You have one line that you commented out, can it just be removed? 
Also, there are 3 commits in this PR but it looks like only the most recent is for fixing this bug. Did you create this branch off an older version of Development? Can we get it cleaned up to make sure nothing unintended gets merged into Development?

**Comment by GreihMurray** [comment]
I made this off the most recent version of develop but apparently there was an older bugfix branch on my local machine so there were some merge conflicts I had to resolve. And yeah, i'll go ahead and remove that line

**Comment by abeiler7** [comment]
Are you able to clean up the branch so that the old commits are not there? It doesn't look like it's introducing any specific issues but it's risky and it makes history really messy and confusing

**Comment by GreihMurray** [comment]
I think I might need to make a new branch instead, those commits are from about a month ago from another bugfix

**Comment by abeiler7** [comment]
Another option would be to do an interactive rebase. The menu that will pop up will let you drop those two old commits

**Comment by GreihMurray** [comment]
I gave an interactive rebase a shot and it started breaking things so I'm just gonna make a new branch and PR

**Pull request closed without merging**
